# general settings
name: 105_EDSR_SN6_0.46_2m_x4_pretrained
model_type: SRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: SN6
    type: PairedImageDataset
    dataroot_gt: datasets/SN6/splitted/train/hr
    dataroot_lq: datasets/SN6/splitted/train/lr
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 512
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 1
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 100
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: SN6
    type: PairedImageDataset
    dataroot_gt: datasets/SN6/splitted/test/hr
    dataroot_lq: datasets/SN6/splitted/test/lr
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: EDSR
  num_in_ch: 4
  num_out_ch: 4
  num_feat: 256
  num_block: 32
  upscale: 4
  res_scale: 0.1
  img_range: 2048.
  channels_mean: [0.08297, 0.07921, 0.05765, 0.18855]

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e2
  save_img: true
  save_img_names: ['5330', '5563', '5595', '5600']

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false
    niqe:
      type: calculate_niqe
      crop_border: 4

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500